// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTc1OUTUHF3IIdDVAux3uRkx-Ey5TusLM',
    appId: '1:682113097700:web:2f597e99cca0710a91b1f1',
    messagingSenderId: '682113097700',
    projectId: 'tubes-mobapp-9c34b',
    authDomain: 'tubes-mobapp-9c34b.firebaseapp.com',
    storageBucket: 'tubes-mobapp-9c34b.appspot.com',
    measurementId: 'G-2VCV4XB0CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp8vgOoOHKO0mWGZ9DU48XH0V1l72tH9g',
    appId: '1:682113097700:android:81901767adc9cb6291b1f1',
    messagingSenderId: '682113097700',
    projectId: 'tubes-mobapp-9c34b',
    storageBucket: 'tubes-mobapp-9c34b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZDT_yj1mIHZ25criT930-p1Ikm7CgRoU',
    appId: '1:682113097700:ios:214c6a1fd7da428891b1f1',
    messagingSenderId: '682113097700',
    projectId: 'tubes-mobapp-9c34b',
    storageBucket: 'tubes-mobapp-9c34b.appspot.com',
    iosClientId:
        '682113097700-oitck526jhaic0ftc5h6cl1ttgpb290k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZDT_yj1mIHZ25criT930-p1Ikm7CgRoU',
    appId: '1:682113097700:ios:86d44e23eaeab56991b1f1',
    messagingSenderId: '682113097700',
    projectId: 'tubes-mobapp-9c34b',
    storageBucket: 'tubes-mobapp-9c34b.appspot.com',
    iosClientId:
        '682113097700-30hbtbp7eganrvkh2954ouosnlflt1ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes.RunnerTests',
  );
}
